default: &default
  adapter: postgresql
  host: <%= Rails.application.secrets[:db_host] %>
  port: <%= Rails.application.secrets[:db_port] %>
  timeout: 5000
  encoding: unicode
  database: <%= Rails.application.secrets[:db_name]%>
  username: <%= Rails.application.secrets[:db_username] %>
  password: <%= Rails.application.secrets[:db_password]%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RentCar_development

test:
  <<: *default
  database: RentCar_test

production:
  <<: *default
  database: RentCar_production
  username: RentCar
  password: <%= ENV['RENTCAR_DATABASE_PASSWORD'] %>
