shared:
  email_from: 'admin@example.com'
  db_username: <%= ENV["DB_USERNAME"] %>
  db_password: <%= ENV["DB_PASSWORD"] %>
  db_name: <%= ENV["DB_NAME"] %>
  db_host: <%= ENV["DB_HOST"] %>
  db_port: <%= ENV["DB_PORT"] %>
development:
test:
production: